"""
Django settings for dj18tests project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os


#
# Settings for pcassandra
#

CASSANDRA_CONNECTION = {
    'KEYSPACE': 'dj18test_app' + os.environ.get('TEST_KEYSPACE_SUFFIX', ''),
    'HOSTS': ['127.0.0.1'],
    'KEYSPACE_REPLICATION': """
        {{
         'class' : 'SimpleStrategy',
         'replication_factor' : {replication_factor}
        }}
    """.format(
        replication_factor=os.environ.get('TEST_KEYSPACE_REPL_FACTOR', '1')
    ),
    'CLUSTER_KWARGS': {
        'protocol_version': 3
    }
}

AUTHENTICATION_BACKENDS = (
    # 'django.contrib.auth.backends.ModelBackend',
    'pcassandra.dj18.auth.backend.ModelBackend',
)

AUTH_USER_MODEL = 'pcassandra.DjangoUserProxy'

PCASSANDRA_AUTH_USER_MODEL = 'pcassandra.dj18.auth.models.CassandraUser'

WSGI_APPLICATION = 'dj18test_app.wsgi.application_development'

SESSION_ENGINE = 'pcassandra.dj18.session.backend'

#
# Django settings
#

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRET_KEY = 'f)%dy9k(e7hz!%hkskp60lu2804_ojpat*ztg6dpn0zx6fdo8p'
DEBUG = True
ALLOWED_HOSTS = []
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # pcassandra + test app
    'pcassandra',
    'dj18test_app',
)
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)
ROOT_URLCONF = 'dj18test_app.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'

# Just to suppress the warnings when running tests.
os.environ['CQLENG_ALLOW_SCHEMA_MANAGEMENT'] = 'yeah'
